pins/tezos-baking-platform/default.nix
fatal: No url found for submodule path 'ledger/nanos-secure-sdk' in .gitmodules
Solution: Bump to tezos-baking-platform with this removed.
Lesson learned: Modify .gitmodules with `git rm <reference>` when
possible (when the reference exists), rather than editing
.gitmodules, to not forget removing the reference later.
But this is also an example of why submodules are best avoided to
begin with. Too many moving parts, too brittle.
=> Problem: Dangling submodule reference (unused) in t-b-p

modules/stakepool.nix
If you add `stakepool.nix` to imports, you need to define
`services.tezos.nodes`, or you'll get:
error: The option 'services.tezos.nodes' is used but not defined.
Solution: Provide a default.
=> Problem: stakepool.nix: Cannot import without configuring

stub-system/configuration.nix
Solution: Configure the stub system with one mainnet, one alphanet node
=> Problem: No test for mainnet

release.nix
Solution: Build for nixos-oldstable and nixos-stable.
On hydra these are currently configured for nixos-18.03 and
nixos-18.09.
=> Problem: Not caching for people running on NixOS channels

support/utils/nix-build-travis-fold.sh
It breaks if your nixpkgs is not in `~/.nix-defexpr/channels/nixpkgs`,
e.g. if you have a `NIX_PATH=nixpkgs=.../root/channels/nixos/nixpkgs`,
which NixOS has by default.
Solution: Take the updated solution from fractalide/racket2nix#170 .
- Evaluate <nixpkgs> instead of guessing.
- Canonicalize link path (`readlink -e ...`).
=>  Problem: ./release.sh does not work on default NixOS

release.nix
```
Oct 02 16:32:50 mail.fractalide.com hydra-evaluator[21368]: starting evaluation of jobset ‘fractalide:tezos-stakepool’ (last checked 600 s ago)
Oct 02 16:33:21 mail.fractalide.com hydra-evaluator[21368]: received jobset event
Oct 02 16:33:22 mail.fractalide.com hydra-evaluator[21368]: hydra-eval-jobs returned exit code 1:
Oct 02 16:33:22 mail.fractalide.com hydra-evaluator[21368]: error: access to path '/nix/store/9445svhcspwaadrm26v2raclw3x4ayc9-q9nhs2f1lpzhmy6knagrahnyviypnvgr-git-export/nixos' is forbidden in restricted mode
Oct 02 16:33:22 mail.fractalide.com hydra-evaluator[21368]: evaluation of jobset ‘fractalide:tezos-stakepool’ failed with exit code 1
```
It worked fine when we referred to <nixpkgs/nixos> etc, so let's go
back to doing that for those paths, but now with a …
=> Problem: Hydra cannot evaluate release.nix

release.nix
I expect some people might be running this, so we might as well
support it. Probably not a huge cost, as it should have a lot of
overlap with nixpkgs-unstable.
Hydra has already been configured to support it.
=> Problem: No nixos-unstable

modules/stakepool.nix, modules/tezos-accuser.sh.nix, modules/tezos-baker.sh.nix, modules/tezos-endorser.sh.nix, modules/tezos-init.sh.nix, stub-system/configuration.nix
No service definitions for accuser, baker and endorser
Solution: Implement baker services.
If a node has `baking.enable = true` (the default):
- Automatically create and alias implicit baker address.
- Run accuser, baker and endorser services.
Issues:
- Haven't verified that it actually bakes.
- No monitoring
- No account management to automatically pay delegators their share
- No documentation
=>  Problem: No baker services

modules/monitor-bootstrapped.sh.nix, modules/stakepool.nix
In particular when an unsynced node comes up, it may take some time
before RPC services become available. If the baker and other services
try to start during this window they will simply fail, and systemd
will not restart them.
If you set `Restart=always`, systemd will restart them 5 times,
then complain that they failed too fast, too often, and then refuse to
ever start them again. (Default limit is 5 restarts within 10
seconds.)
Same if you set a check in `ExecStartPre` and let it just fail.
Solution: Let ExecStartPre wait until the RPC service is available.
Closes #19
Also takes care of the case where you bring down the node for some
reason, then bring it back up.
The services will be in state `activating` until the RPC comes up,
then ExecStart will run, and the services will be …
=> Problem: Services may start too fast

modules/tezos-init.sh.nix
Solution: Run gen keys as the baker user.
=> Problem: tezos-init: baker key generated as root

modules/tezos-run.sh.nix
curl is too silent. We don't want the progress bar, but if it e.g. has
network issues, we need to see that in the log.
Solution: Use -S, not -s.
=> Problem: tezos-run: curl fails without explanation

modules/tezos-init.sh.nix
Expected to find data directory version file at
'/etc/nixos/secret/tezos-alphanet/version.json',  but the file
does not exist.
Not detected because works on my machine (file already generated).
Solution: Initialize node before client.
Closes #32
=> Problem: tezos-init: Generating address before identity

pins/tezos-baking-platform/default.json
That's because in the sandbox there is no /usr/bin/env.
Solution: Bump tezos-baking-platform.
- Make all OPAM packages run patchShebangs in postPatch.
- If any package redefines postPatch, the package's own postPatch
takes priority.
=> Problem: Zarith (so, Tezos) does not build in the Nix sandbox

modules/stakepool.nix, modules/tezos-baker-stats.sh.nix
We always store and parse the head of the chain, but unless it happens
to be the last block of a cycle, it becomes irrelevant when the next
block comes around.
'blocks' holds the relevant blocks -- the current head and the last
blocks of all preceding cycles.
Solution: At the end of baker-stats, remove all cached blocks not in 'blocks'.
=> Problem: baker-stats: Leaving outdated blocks around

modules/stakepool.nix
Solution: Run as baker user, wait for node to be up before running.
=> Problem: baker-stats: May fail to run, runs as root

modules/default.nix, stub-system/configuration.nix
Convention demands a modules.nix or a modules/default.nix.
Solution: Add modules/default.nix, which imports stakepools.nix.
Make the stub-system use modules instead of modules/stakepools.nix.
=> Problem: No modules/default.nix

modules/tezos-baker-stats.sh.nix
In blocks before the baker account existed, the delegates helper will
return 'Unexpected server answer'.
Solution: Detect this, and default to '[]'.
=> Problem: baker-stats: delegate.json: Not always valid JSON

modules/tezos-baker-stats.sh.nix
This is not a big issue, especially when running inside the service,
which provides the PATH from the buildInputs, but I feel better having
absolute references everywhere when running this outside the service
(e.g. for testing).
Solution: Prefix all coreutils calls with the coreutils path.
=> Problem: baker-stats: Relies on correct PATH

modules/stakepool.nix, modules/tezos-baker-stats.sh.nix
Solution: Get all frozen rewards in history, calculate distribution.
Generate for each snapshot cycle rewards.json, collate in global
rewards.json.
The format is an array of objects with cycle, staker, reward, so this
is ready for being put in a table on the website.
Issues:
- The distribution is based on the final level of each cycle,
and can be gamed. Fairer would be a random sample -- not
necessarily the same as the one Tezos chose, but it would have to
at least be reproducible after the fact, but not predictable
beforehand.
- The fairest measure would be the average staking balance over the
whole snapshot cycle, but that's expensive in storage and time.
=> Problem: No per-account distributed rewards

modules/tezos-baker-stats.sh.nix
As a staker, I want to know when I will get my money. When it was
earned is a technical detail.
Solution: Record rewards for the cycle the will be paid out.
Which cycle directory the file is in doesn't matter, what matters is
the 'cycle' field. All rewards.json files are just concatenated
anyway.
=> Problem: Rewards are shown for the cycle they were earned

modules/tezos-baker.sh.nix, modules/tezos-init.sh.nix
Generating the keys for the baker is done with an RPC call.
Solution: Move baker key gen to the baker service.
As an added benefit we don't need to switch users, because the service
is already running as the non-root user.
=> Problem: tezos-init needs node running

modules/tezos-baker-stats.sh.nix
The jq function won't be used by xargs, so it will rely on PATH to
find jq.
Solution: Prefix jq with the absolute path when called with xargs.
- Found an rm call that should have an absolute prefix.
- printf is an internal bash command, but when used with xargs, it's
the coreutils printf.
=> Problem: xargs cannot make use of a bash function

modules/stakepool.nix, modules/tezos-baker-stats.sh.nix
You cannot trivially run the stats on an arbitrary account.
Solution: Split out the stats script from the stats service.
Still not super convenient, but at least you can read the service,
read the service script, and then find the stats script and run it
with your choice of output dir and account address.
It's a first step.
=> Problem: Baker account is compiled into the stats script.

modules/tezos-baker-stats.sh.nix
The addressOrName conditional is exactly backwards.
We make an address lookup when we get a literal address:
Error:
Erroneous command line argument 3 (tz1...).
no public key hash alias named tz1...
And we use the alias in RPC calls when we get an address alias:
Error:
Did not find service
Solution: Correct the literal address detection.
=> Problem: baker-stats: The address lookup does not work

pkgs/default.nix
error: attribute 'ghc843' missing, at /nix/store/1ihy9p4cf2y2dpfr03bg5m3li26w9q8c-source/release.nix:4:14
This is when building Bäckerei.
Solution: Override the compiler, use ghc844 if available.
=> Problem: Does not build with nixos-unstable

release.nix
The lib.versioning fix in obsidian.systems/tezos-baking-platform#23 [0]
requires a nixpkgs from 2018-04 or later.
Solution: Remove nixos-oldstable from release.nix.
[0] https://gitlab.com/obsidian.systems/tezos-baking-platform/merge_requests/23
[0] https://github.com/fractalide/tezos-baking-platform/commit/3cfde6c9b068b57a09c576f14e0ec5f79e7e1157
=> Problem: nixos-18.03 is not compatible with tezos-baking-platform

modules/stakepool.nix, modules/tezos-accuser-old.sh.nix, modules/tezos-accuser.sh.nix, modules/tezos-baker-old.sh.nix, modules/tezos-endorser-old.sh.nix, modules/tezos-endorser.sh.nix, pins/tezos-baking-platform/bump.sh, pins/tezos-baking-platform/default.json
Solution: Bump fractalide/tezos-baking-platform#8 .
- Use the new and shorter bump.sh from
fractalide/tezos-baking-platform , which is entirely generic
instead of having embedded configuration.
- To change where the pin is pointing, just do a 'nix-prefetch-git'
to the JSON and bump.sh will pick it up next time.
----
Problem: accuser baker endorser: old protocol
Solution: Run the binaries for the new protocol.
The old protocol is safe to run in parallel, the services will become
inactive at fork time. We'll remove them again when this has happened.
I'm adding some copy-paste for this emergency fix. Next time this
happens, we'll have something neater in store.
=>  Problem: Not updated for protocol 003-PsddFKi3

pins/tezos-baking-platform/default.json
Solution: pull in our latest n greatest which contains these fixes
003/Baker: fix nonce revelation from old 002 blocks
Baker: prevent nonces revelation to crash the baker
=> Problem: tezos-bake-platform bumped

default.nix
This means dependents need to do things like:
imports = [ ((import pins/fractalpools) + "/modules") ];
(where pins/fractalpools is some `fetchgit { . . . }`)
Solution: Make ./modules an attribute 'modules' at the top level.
Now you can depend with an auto-importing pin and just:
imports = [ (import pins/fractalpools).modules ];
(where pins/fractalpools is some `import (fetchgit { . . . })`)
It also helps with restrict-eval issues.
=> Problem: No top-level default.nix
